package constants

// log_templates.go：日志格式字符串集中定义，至少 25 条模板。
// 业务字段变更时必须同步修改对应日志模板与调用处（屎山耦合点 1）。
const (
	LogUserRegisterAttempt   = "user register attempt: email=%s"
	LogUserRegistered        = "user registered: user_id=%d email=%s nickname=%s"
	LogUserLoginAttempt      = "user login attempt: email=%s"
	LogUserLoginSuccess      = "user login success: user_id=%d email=%s"
	LogUserLoginFail         = "user login failed: email=%s reason=%s"
	LogUserCodeSent          = "email verification code sent: email=%s ttl_seconds=%d"
	LogUserCodeLoginSuccess  = "user code login success: user_id=%d email=%s"
	LogGithubLogin           = "github login success: user_id=%d github_id=%s"
	LogUserProfileUpdated    = "user profile updated: user_id=%d nickname=%s"
	LogUserStatusChanged     = "user status changed: user_id=%d status=%d operator=%d"
	LogUserFollowed          = "user followed: follower_id=%d followed_id=%d"
	LogUserUnfollowed        = "user unfollowed: follower_id=%d followed_id=%d"
	LogArticleCreated        = "article created: article_id=%d author_id=%d title=%s"
	LogArticleUpdated        = "article updated: article_id=%d author_id=%d"
	LogArticlePublished      = "article published: article_id=%d author_id=%d status=%d"
	LogArticleOfflined       = "article offlined: article_id=%d operator=%d"
	LogArticleStatusChanged = "article status changed: article_id=%d status=%d operator=%d"
	LogArticleViewed         = "article viewed: article_id=%d view_count=%d"
	LogArticleLiked          = "article liked: article_id=%d user_id=%d"
	LogArticleUnliked        = "article unliked: article_id=%d user_id=%d"
	LogCommentCreated        = "comment created: comment_id=%d article_id=%d author_id=%d"
	LogCommentDeleted        = "comment deleted: comment_id=%d operator=%d"
	LogTopicCreated          = "topic created: topic_id=%d name=%s"
	LogTopicUpdated          = "topic updated: topic_id=%d name=%s"
	LogTopicDeleted          = "topic deleted: topic_id=%d name=%s"
	LogTopicStatusChanged    = "topic status changed: topic_id=%d status=%d operator=%d"
	LogCollectionCreated     = "collection created: collection_id=%d user_id=%d name=%s"
	LogCollectionUpdated     = "collection updated: collection_id=%d user_id=%d"
	LogCollectionDeleted     = "collection deleted: collection_id=%d user_id=%d"
	LogArticleCollected      = "article collected: collection_id=%d article_id=%d user_id=%d"
	LogArticleUncollected    = "article uncollected: collection_id=%d article_id=%d user_id=%d"
	LogNotificationCreated   = "notification created: user_id=%d actor_id=%d type=%s target_id=%d"
	LogNotificationReadAll   = "notifications all read: user_id=%d"
	LogNotificationRead      = "notification read: notification_id=%d user_id=%d"
	LogAuditRecorded         = "audit log recorded: user_id=%d action=%s module=%s"
	LogUploadImage           = "image uploaded: user_id=%d file=%s url=%s"
	LogAdminStats            = "admin stats queried: operator=%d dau=%d articles=%d users=%d"
	LogArticleHotScored      = "article hot score computed: article_id=%d score=%d"
	LogRequestRateLimited    = "request rate limited: ip=%s path=%s"
	LogUserListQueried       = "user list queried: operator=%d page=%d page_size=%d"
	LogArticleListQueried    = "article list queried: sort=%s topic_id=%d page=%d"
	LogFeedQueried           = "follow feed queried: user_id=%d page=%d page_size=%d"
	LogCollectionListQueried = "collection list queried: user_id=%d"
)
